### ISSUE TITLE
[DISCUSSION] My first look at the game

### ISSUE THREAD

**Issue by Vihershunde** [WarFrontIO/client#1]
It's really nice idea and I like how countries are spreading on the map. 
Waiting for:
-Boats
-Menu
-In-game leaderboard 
-Multiplayer
-More interactivity (A single click for the attack is quite intuitive.)

Some of my ideas:
-Chat or more emojis would be crazy! It would make it totally different game from Territorial.io
-Supply hubs and lines around cities, military access and encirclements at least in one game mode.
-Vassal states

Also I think you need webpack dev server installed to run game.
All in all, very good project, go on!

**Comment by platz1de** [comment]
For discussions, please head over to our discord server (I've added the link to the readme)

About webpack dev server:
The main build should run perfectly fine without it (it doesn't load any external resources), other things (e.g. editing raw menu files) might require a local webserver (the webpack one will probably result in a refresh loop though as it requires manual configuration on which files to ignore, I won't provide direct support for that)
