### ISSUE TITLE
White Screen Issue with Dark Reader Enabled

### ISSUE THREAD

**Issue by Ahmadjerj** [WarFrontIO/client#16]
### Expected Behavior

The website should be displayed normally, albeit with a darkened appearance due to the Dark Reader extension. If the website is still not displaying correctly, the extension should be disabled to restore normal visibility and usability.

### Actual Behavior

After selecting the "Singleplayer" option, the website displays a completely white screen (#DDECF5), making it impossible to view or interact with the content.

### Steps to Reproduce

1. Install the Dark Reader extension.
2. Configure Dark Reader settings as desired.
3. Click on the "Singleplayer" button on the website.

### Which browser are you using?

Chrome

### If you selected "Other", please specify

/ Firefox

### Additional Information

To resolve this issue, you can use one of the following methods:

   Add the following <meta> tag directly to the <head> section of your HTML:
``` bash
<head>
    <meta name="darkreader-lock">
</head>
```

**Comment by ahmadjerjawi** [comment]
<head>
    <meta name="darkreader-lock">
</head>
