### ISSUE TITLE
Dedicated place for documentation to live

### ISSUE THREAD

**Issue by esk33** [WarFrontIO/client#7]
Currently documentation kinda just lives in JSDoc comments and some markdown files inside the source code itself (`MODULES.md`, `HUD.md` for example). It might be a good idea to move documentation to a dedicated site (`docs.warfront.io`?), GitHub wiki, or something of the like, rather than directly in the source code.

**Comment by platz1de** [comment]
This isn't a library, contributing requires looking in the source code anyways. Moving docs somewhere else only complicates things by requiring a search to find the appropriate information
Mod support (which would benefit from packagedocs) is too far into the future to justify the effort now.
